# This file has be generated by Tricky's MyData
# 22 Feb 2017; 22:48:28
# License: If stripped from any reference to the story line and its characters, this file becomes zLib
INSERT INTO `mytable` set 
		`Description` = "Collect all of Crystal's special arrows for her bionic arm",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Wild Arms",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Unlock all moves for either ExHuRU, Rolf or Johnson",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Hasta la vista, baby",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Unlock all of Foxy's special moves",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "I'm Sexy and I know it",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Obtain all abilities Wendicka can get",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "It's ELECTRIFYING",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Unlock all of Xenobi's \"power\" spells",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "May the power be with you",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Unlock all of Yirl's special moves",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Great shot, kid! That was one in a million!",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Have one male character make at least one step",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "A small step for man, but a giant leap for mankind",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Visit Wendicka's & Crystal's home during the final mission.",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Home, sweet home.",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Reach the room where the \"Rising Nova\" ARM for Crystal is stored",
		`Icon` = "GFX/Achievements/ALLABL_Crystal.png",
		`Show` = "Always",
		`Title` = "Super Nova",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Find the secret cyborg laboratory",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Seek and you will find",
		`Type` = "Platinum"


INSERT INTO `mytable` set 
		`Description` = "Defeat Dard Boorth in the Black Castle",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Bull's Eye",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Defeat the Black Hole Dweller",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "There is no life... in the void",
		`Type` = "Platinum"


INSERT INTO `mytable` set 
		`Description` = "Defeat George McLeen in Excalibur",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Bitter Sweet Victory",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Defeat Mid-Boss",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "The Dark Adonis",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Defeat SuperCyborg",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Is it a bird? Is it an airplane?",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Do your first kill!",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "He's dead, Jim!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Kill 394 enemies",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Turn to page 394!",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Make 800 kils",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Heel gewoon DOODgewoon",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Have Crystal at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Resistance is futile",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Have ExHuRU, Rolf or Johnson at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "I'll be back",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Have Foxy at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "I'm too sexy for this game!",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Have Wendicka at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Somewhere over the rainbow",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Have Xenobi at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "I've got the power!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Have Yirl at  at level 10,000 (requires multiple playthroughs)",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Never tell me the odds",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Have a streak of five perfect victories",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Five nights at Wendicka's",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Win a battle without receiving any damage.",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "It's got to be PERFECT!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Win 10 victories without taking damage",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "It's such a perfect day",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Have one of the female characters to speak to Rick outside the bar",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Rickrolled",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Use the save terminal on board the Hawk at least 30 times",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Marked for Review",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Use a teleport pad to beam yourself up to the Hawk at least once",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Beam me up, Scotty!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Have Foxy to destroy the equipment and reveal that this is all a film on set",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Crash! Bang! Uncooth!",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Discover the role of Crystal's father in the story",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "The Undiscovered Bounty",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Defeat Diablo in Marlon's garden",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "There is no secret cow level!",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Escape the space station Excalibur",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "To boldly go where no one has gone before",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Enter the final dungeon",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "The Final Frontier",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Release the Goddess from Wendicka",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "It's life, Jim, but not as we know it",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Find the galaxy of Phantasar",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "Long ago in a galaxy far away",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Complete the Ghost House",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "I ain't afraid of no ghost",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Complete the prologue",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "You are NOT prepared!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Meet Wendicka's biological father",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "No! I am your father!",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Discover Wendicka is pregnant",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "The Next Generation",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Complete \"Dark Caves of Shilington\"",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Beware of the Dark Side",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Complete the secret dungeon: Dark Graveyard",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Death Becomes Her",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Complete the Eugorvnia Caves",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Under(the)city",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Complete \"Observatorium\"",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "A clever observation",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Complete the sewers",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "It's alive.... ALIVE!!!!",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Complete the Volcania Caves",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "We didn't start the fire",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Foxy spoke French! Alas, Gomez wasn't around!",
		`Icon` = "*DEFAULT*",
		`Show` = "Achieved",
		`Title` = "She spoke French! SHE SPOKE FRENCH!",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Survive being hit by instant kill because you were either damned or a zombie",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Not today!",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Become a zombie",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "What's in your head? Zombie! Zombie!",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Win 17 battles",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "True Q",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Win 25 battles",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Twenty Five",
		`Type` = "Bronze"


INSERT INTO `mytable` set 
		`Description` = "Win 50 battles",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Fifty Shades of Grey",
		`Type` = "Silver"


INSERT INTO `mytable` set 
		`Description` = "Win 100 battles",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "The 100",
		`Type` = "Gold"


INSERT INTO `mytable` set 
		`Description` = "Win 1000 battles",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "A thousand years",
		`Type` = "Platinum"


INSERT INTO `mytable` set 
		`Description` = "Complete the game",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "We are the Heroes of our Time",
		`Type` = "Platinum"


INSERT INTO `mytable` set 
		`Description` = "Complete the Block Shooter Mini game with a perfect score of 10 hits",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Perfect Game",
		`Type` = "Platinum"


INSERT INTO `mytable` set 
		`Description` = "Win the shooting game against Kota",
		`Icon` = "*DEFAULT*",
		`Show` = "Always",
		`Title` = "Shoot-'em-up!",
		`Type` = "Silver"



